name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Check:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        node-version: [ '12', '14', '16' ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} / Node ${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install --frozen-lockfile
      - name: Check Types
        run: npm run lint:typecheck
      - name: Lint ESLint
        run: npm run lint:eslint
      - name: Lint Prettier
        run: npm run lint:prettier
      - name: Code Test
        run: npm run test
